FROM ubuntu

RUN apt -y update

RUN apt -y install default-jre

RUN apt -y install default-jdk

RUN apt -y install make

COPY ["/tools/NeuralNetwork", "/NeuralNetwork"]
COPY ["/tools/ProgramForMockData", "/ProgramForMockData"]

WORKDIR /NeuralNetwork

COPY . .

CMD make && make run