---
name: CI Tests

on: 
  push:
    branches: [main,develop]
 
  workflow_dispatch:
    inputs:
      testchoice:
        type: choice
        description: 'Test Type'
        required: true
        options:
        - full
        - lint
        - build
        - unit
        - e2e
        - all
