name: Deploy

on:

  push:
    branches: [ "testDeploy" ]


jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: install dep
        run: yarn install
 
      - name: build api
        run: npx nx build api
        
  redeploy:
  
    runs-on: ubuntu-18.04
    
    steps:
    
    - name: Deploy docker container webhook
      uses: joelwmale/webhook-action@master
      env: 
        WEBHOOK: ${{ secrets.DEPLOY_WEBHOOK_URL }}
      
  
        
    
