name: Deploy

on:

  push:
    branches: [ "testDeploy" ]


jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: install dep
        run: yarn install
 
      - name: build api
        run: npx nx build api
        
  redeploy:
  
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Webhook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
