name: Deploy

on:

  push:
    branches: [ "testDeploy" ]


jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: install dep
        run: yarn install
 
      - name: build api
        run: npx nx build api
        
      - name: build client
        run: npx nx build client
        
      - name: build image for db
        run: docker-compose up -d
        
      - name : assign tag to db
        run : docker tag postgres:13 ${{ secrets.DOCKER_REPO }}:db
        
      - name : build api docker image
        run : docker build -f Dockerfile.api --tag ${{ secrets.DOCKER_REPO }}:api .
        
      - name : build client docker image
        run : sudo docker build -f Dockerfile.client --tag ${{ secrets.DOCKER_REPO }}:client .
        
      - name : login to Docker Hub
        run : docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
        
      - name : push api to docker
        run : docker push ${{ secrets.DOCKER_REPO }}:api
        
      - name : push client to docker
        run : docker push ${{ secrets.DOCKER_REPO }}:client
        
      - name : push db to docker
        run : docker push ${{ secrets.DOCKER_REPO }}:db
        
        
        
  redeploy:
  
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Webhook Test
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
