name: Deploy

on:

  push:
    branches: [ "testDeploy" ]


jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: nrwl/nx-set-shas@v3

 
      - name: build api
        run: nx build api
