name: Test

on:

  push:
    branches: ["TimosBranch"]

jobs:

  integration_test:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: install dep
        run: yarn install

      - name: build image for db
        run: docker-compose up -d
        
      - name: create db schema
        run: yarn prisma migrate dev && yarn prisma generate

